AyudaContable/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
import usuario.views
import superadmin.views
import administrador.views
import usuario.views
#para las fotos
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.views import logout_then_login


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^superadmin/alta_de_administrador/$',superadmin.views.altaAdmin.as_view(), name='altaAdmin'),
    url(r'^superadmin/alta_de_usuario/$',superadmin.views.altaUsuario.as_view(), name='altaUsuario'),
    url(r'^superadmin/index/$',superadmin.views.index0, name='index0'),
    url(r'^administrador/index/$',administrador.views.index1,name='index1'),
    url(r'^administrador/subida/$',administrador.views.subidaXML,name='subidaXML'),
    url(r'^administrador/documentos/$',administrador.views.archivosDB, name='vistaDocumentos'),
    url(r'^administrador/usuarios/$',administrador.views.usuariosACargo,name='usuariosACargo'),
    url(r'^logout$', logout_then_login, name='logout' ),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], superadmin.views.protected_serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^',include('usuario.urls' )),
]

usuario/urls.py
from django.conf.urls import *
from usuario import views

urlpatterns = [
	url(r'^$',views.login, name='index'),
	url(r'^login/$',views.login, name='login'),
	url(r'^redi/$',views.redirecionDeEspacio,name='redi'),
	url(r'^usuario/index/$',views.index3,name='index3'),
	url(r'^usuario/documentos/$',views.archivosGeneral,name='vistaGeneral'),
	url(r'^usuario/documentosN/$',views.leerXMLN,name='vistaN'),
	url(r'^usuario/documentosE/$',views.leerXMLE,name='vistaE'),
	url(r'^usuario/documentosI/$',views.leerXMLI,name='vistaI'),
	url(r'^usuario/documentosP/$',views.leerXMLP,name='vistaP'),
	url(r'^usuario/documentosScript/$',views.leerXMLScript,name='vistaScript'),
	url(r'^usuario/firma/$',views.firmaContrato,name='firmaUsuario'),
	url(r'^usuario/firmaCiec/$',views.firmaCiec,name='firmaCiec'),
	url(r'^usuario/solicitar/$',views.solicitarFactura,name='solicitarFactura'),
	url(r'^usuario/referencia/$',views.generarOxxoPay,name='generarReferencia'),
	url(r'^webhook/$',views.webhook,name='webhook'),
]

usuario/models.py
from django.db import models

# Create your models here.
from superadmin.models import User
from administrador.models import Administrador
import os
from django_cryptography.fields import encrypt
import datetime
import conekta
from datetime import datetime 

def upload_e_firma(self, filename):
    return u'documentos/client_{0}/{1}'.format(self.email.id, filename)

class Usuario(models.Model):
    email = models.OneToOneField(User, on_delete=models.CASCADE)
    RFC = models.CharField(max_length=15,null=True)
    tipo_persona = models.CharField(max_length=15,null=True)
    razon_social = models.CharField(max_length=100,null=True,unique=True)
    direccion_fiscal = models.CharField(max_length=125, null=True)
    e_firma_key = models.FileField(upload_to=upload_e_firma,null=True)
    e_firma_cer = models.FileField(upload_to=upload_e_firma,null=True)
    clave_privada = encrypt(models.CharField(max_length=50))
    ciec = encrypt(models.CharField(max_length=50))
    contador = models.ForeignKey(Administrador, on_delete=models.CASCADE, blank=True, null=True,related_name="contador_personal")    
    def __str__(self):
        return self.email.nombre_completo
    
    class Meta:
        
        permissions = (
            ('is_user', 'Is_User'),
            )

class Cliente(models.Model):
	nombre_completo = models.CharField(max_length=200, null=True)
	razon_social = models.CharField(max_length=200,null=True)
	direccion = models.CharField(max_length=200, null=True)
	RFC = models.CharField(max_length=10,null=True)
	contador =  models.ForeignKey(Usuario,on_delete=models.CASCADE,blank=True, null=True, related_name="cliente_personal")

	def __str__(self):
		return self.RFC.nombre_completo

def upload_to(self, filename):
    return u'documentos/user_{0}/client_{1}/{2}'.format(self.contador.id,self.usuario.id, filename)

def upload_factura(self, filename):
    return u'documentos/user_{0}/client_{1}/{2}{3}-{4}/{5}'.format(self.contador.id,self.usuario.id,self.tipo,self.fecha.year,self.fecha.month, filename)

class Factura(models.Model):
    subido_el = models.DateTimeField(auto_now_add=True)
    contador = models.ForeignKey(Administrador, on_delete=models.CASCADE, blank=True, null=True,related_name="contadorACargo")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True,related_name="FDI")
    xml = models.FileField(upload_to=upload_factura)
    pdf = models.FileField(upload_to=upload_factura)
    fecha = models.DateTimeField(null=True)#format='%Y-%m',input_formats=['%Y-%m'], null=True)
    tipo = models.CharField(max_length=1,null=True)
    RFC = models.CharField(max_length=14,null=True)
    razon_social = models.CharField(max_length=100,null=True)
    vigente = models.BooleanField(default=True)
    sub_total = models.FloatField(null=True)
    total = models.FloatField(null=True)

    def __str__(self):
        return razon_social+str(fecha)

    def filename(self):
        return os.path.basename(self.xml.name)

#    def clean(self):
#        xml = self.cleaned_data.get("xml", False)
#        filetype = magic.from_buffer(xml.read())
#        if not "XML" in filetype:
#            raise ValidationError("File is not XML.")
#        return self.cleaned_data 

class PagoServicio(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True,related_name="cargo_a_usuario")
    referencia = models.CharField(max_length=100,null=True)
    id_orden = models.CharField(max_length=22,null=True)
    estado_de_la_orden = models.CharField(max_length=30,null=True)
    monto = models.CharField(max_length=10,null=True)
    fecha_creado = models.DateTimeField(default=datetime.now, blank=True)

    
    def __str__(self):
        return str(self.referencia)

usuario/forms.py
from django import forms
from usuario.models import Usuario

class FirmaForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('e_firma_key', 'e_firma_cer','clave_privada',)

class FirmaCiec(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('ciec', )

usuario/views.py
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.shortcuts import render,redirect,HttpResponse
from django.contrib import auth
from django.http import HttpResponseRedirect
from superadmin.models import User
from usuario.models import Factura, Usuario,PagoServicio
from xml.dom import minidom
from django.core import serializers
import datetime
import os
from usuario.forms import FirmaForm, FirmaCiec
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.db.models import Sum

# Create your views here.
def login(request):
    if  request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        user = auth.authenticate(email = email, password = password)
        if user is not None:
            auth.login(request, user)
            return redirect('redi')
        else:
            mensaje = "Error credenciales no validas"
            return render(request,'login.html',{'mensaje':mensaje})
    else:
        return render(request,'login.html')

@login_required
def firmaContrato(request):
    if request.method == 'POST':
        instance = Usuario.objects.get(email=request.user.id)
        form = FirmaForm(request.POST, request.FILES,instance = instance)
        vacio="entro en POST"
        if form.is_valid():
            instance = form.save(commit=False)
            instance.email = request.user
            instance.save()
            vacio="paso por el form"
            return redirect('index3')
        else:
            pass
    else:
        vacio="entro en nada"
    return render(request,'usuario/index.html',{'vacio':vacio})

@login_required
def firmaCiec(request):
    if request.method == 'POST':
        instance = Usuario.objects.get(email=request.user.id)
        form = FirmaCiec(request.POST, request.FILES,instance = instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.email = request.user
            instance.save()
            return redirect('index3')
        else:
            pass
    else:
        vacio="entro en nada"
    return render(request,'usuario/index.html',{'vacio':vacio})

@login_required
def redirecionDeEspacio(request):
	return render(request,'redirecion.html')

@login_required
def index3(request):
    usuario = User.objects.get(email=request.user.email)
    usuario = Usuario.objects.get(email=usuario.id)
    falta_ciec = None
    firmo = None
    if usuario.e_firma_key == "" and usuario.e_firma_cer == "" and usuario.clave_privada ==  "":
        firmo = False
    else:
        firmo = True
    if firmo and usuario.ciec == "":
        falta_ciec = True
    else:
        falta_ciec = False
    return render(request,'usuario/index.html',{'firmo': firmo,'falta_ciec':falta_ciec})

@login_required
def archivosGeneral(request):
    usuario = User.objects.get(email=request.user.email)
    usuar = Usuario.objects.get(email=usuario.id)
    archivos = Factura.objects.filter(contador=usuar.id)
    return render(request,'usuario/documentosDB.html', {'documentos': archivos})

@login_required
def leerXMLScript(request):
    datos = []
    if request.method == 'GET':
        fecha = request.GET['fecha']
        tipo = request.GET['tipo']
        fecha = datetime.datetime.strptime(fecha,"%Y-%m")
        anio = fecha.year
        mes = fecha.month
        usuar = Usuario.objects.get(email=request.user.id)
        cfdis = Factura.objects.filter(usuario=usuar.id,fecha__month=mes,fecha__year=anio)
        tabla = serializers.serialize('json',cfdis)
        return HttpResponse(str(tabla))
    else:
        pass

@login_required
def leerXMLN(request):
    tipo = 'N'
    hoy = datetime.date.today()
    usuar = Usuario.objects.get(email=request.user.id)
    cfdis = Factura.objects.filter(usuario=usuar.id,fecha__month=hoy.month,fecha__year=hoy.year,tipo=tipo)
    total=0
    for cfdi in cfdis:
        total+=cfdi.total
    return render(request,'usuario/documentosDB.html',{'tipo':tipo,'facturas':cfdis,'total':total})

@login_required
def leerXMLI(request):
    tipo = 'I'
    hoy = datetime.date.today()
    usuar = Usuario.objects.get(email=request.user.id)
    cfdis = Factura.objects.filter(usuario=usuar.id,fecha__month=hoy.month,fecha__year=hoy.year,tipo=tipo)
    total=0
    for cfdi in cfdis:
        total+=cfdi.total
    return render(request,'usuario/documentosDB.html',{'tipo':tipo,'facturas':cfdis,'total':total})

@login_required
def leerXMLE(request):
    tipo = 'E'
    hoy = datetime.date.today()
    usuar = Usuario.objects.get(email=request.user.id)
    cfdis = Factura.objects.filter(usuario=usuar.id,fecha__month=hoy.month,fecha__year=hoy.year,tipo=tipo)
    total=0
    for cfdi in cfdis:
        total+=cfdi.total
    return render(request,'usuario/documentosDB.html',{'tipo':tipo,'facturas':cfdis,'total':total})

@login_required
def leerXMLP(request):
    tipo = 'P'
    hoy = datetime.date.today()
    usuar = Usuario.objects.get(email=request.user.id)
    cfdis = Factura.objects.filter(usuario=usuar.id,fecha__month=hoy.month,fecha__year=hoy.year,tipo=tipo)
    total=0
    for cfdi in cfdis:
        total+=cfdi.total
    return render(request,'usuario/documentosDB.html',{'tipo':tipo,'facturas':cfdis,'total':total})

@login_required
def solicitarFactura(request):
    return render(request,'usuario/solicitudFactura.html')

def generarOxxoPay(request):
    import conekta
    conekta.api_key = "key_vssXxqzYzDLz7Hfz2yPyrQ"
    conekta.api_version = "2.0.0"
    hoy = datetime.date.today()
    mes_actual = hoy.month
    usuario = Usuario.objects.get(email=request.user.id)
    orden = PagoServicio.objects.filter(usuario=usuario,fecha_creado__month=mes_actual)
    if orden.count() != 0:
        referencia = orden.referencia
        monto = orden.monto
    else:
        order = conekta.Order.create({
            "line_items": [{
            "name": "Tacos",
            "unit_price": 10000,
            "quantity": 1
            }],
            "currency": "MXN",
            "customer_info": {
            "name": "Fulanito Pérez",
            "email": "fulanito@conekta.com",
            "phone": "+5218181818181"
            },
            "shipping_contact":{
            "address": {
            "street1": "Calle 123, int 2",
            "postal_code": "06100",
            "country": "MX"
            }
            }, #shipping_contact - required only for physical goods
            "charges":[{
            "payment_method": {
            "type": "oxxo_cash"
            }
            }]
            })
        monto=str(order.amount/100)
        referencia=order.charges[0].payment_method.reference
        referencia=referencia[0:4]+"-"+referencia[4:8]+"-"+referencia[8:12]+"-"+referencia[12:14]
        orden= PagoServicio()
        orden.referencia=referencia
        orden.monto=monto
        orden.estado_de_la_orden = order.payment_status
        orden.id_orden = order.id
        orden.usuario =usuario
        orden.save()
    return render(request,'usuario/OxxoPay.html',{'referencia':referencia,'monto':monto})

@csrf_exempt
@require_POST
def webhook(request):
    import json
    data = json.loads(request.body)
    if data["type"] == 'charge.paid':
        from usuario.correo import Correo
        email=Correo()
        email.enviarCorreo("alexskullsoft@gmail.com","Alexis Eduardo Silva Bautista")
    elif data["type"] == 'order.paid':
        #print(data["data"]["object"]["charges"]["data"][0]["order_id"])
        from usuario.correo import Correo
        email=Correo()
        email.enviarCorreo("alexskullsoft@gmail.com","Alexis Eduardo Silva Bautista")
    else:
        pass
    return HttpResponse(status=200)

"""def clasificar(tipo,cfdis):
    mensaje=""
    data = json.loads(HttpRequest.body)
    if data.type == 'charge.paid':
        msg['Subject'] = 'Pago confirmado'
        msg['From'] = me
        msg['To'] = you
        mensaje="exitoso"
    s = smtplib.SMTP('localhost')
    s.sendmail(me, [you], msg.as_string())
    s.quit()
    return render(request,'usuario/OxxoPay.html')
def clasificar(tipo,cfdis):
    documentos=[]
    for x in cfdis:
        y=minidom.parse(os.getcwd()+"/media/"+str(x.xml))
        lineas=y.getElementsByTagName("cfdi:Comprobante")
        for linea in lineas:
            z=linea.getAttribute("TipoDeComprobante")
            if z == tipo:
                documentos.append(x)
            else:
                pass
    return documentos

def entablar(xmls):
    tabla = []
    for a in xmls:
        tablatemp = []
        descargartmp = []
        x = a.xml
        descargartmp.append(x)
        y = a.pdf
        descargartmp.append(y)
        tablatemp.append(descargartmp)
        b=minidom.parse(os.getcwd()+"/media/"+str(a.xml))
        lineas = b.getElementsByTagName("cfdi:Receptor")
        c=lineas[0].getAttribute("Rfc")
        d=lineas[0].getAttribute("Nombre")
        tablatemp.append(c)
        tablatemp.append(d)
        lineas2 = b.getElementsByTagName("cfdi:Comprobante")
        e=lineas2[0].getAttribute("Fecha")
        f=lineas2[0].getAttribute("SubTotal")
        g=lineas2[0].getAttribute("Total")
        tablatemp.append(e)
        tablatemp.append("SI")
        tablatemp.append(f)
        tablatemp.append(g)
        tabla.append(tablatemp)
    return tabla
@login_required
def leerXMLN(request):
    tipo = 'N'
    usuar = Usuario.objects.get(email=request.user.id)
    cfdis = Factura.objects.filter(usuario=usuar.id)
    xmls = clasificar(tipo,cfdis)
    tabla = entablar(xmls)
    hoy = datetime.date.today()
    mes = hoy.month
    anio = hoy.year
    tabla = filtrarMes(tabla,mes,anio)
    total = totalDelMes(tabla)
    return render(request,'usuario/documentosDB.html', {'tabla':tabla,'total':total,'tipo':tipo})

@login_required
def leerXMLI(request):
    tipo = 'I'
    usuar = Usuario.objects.get(email=request.user.id)

templates/usuario/index.html
{% extends 'usuario/plantilla.html' %}
{% load static %}
  {% block title %} Inicio {% endblock %}
  {% block menubar %}{% include "usuario/menu.html" %}{% endblock %}
{% block archivos %}
<link href="{% static 'css/plugins/jasny/jasny-bootstrap.min.css' %}" rel="stylesheet"> 
<script>
function ShowCIEC(){
    var x = document.getElementById("ciec");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}
</script>
<script>
function ShowPass(){
    var x = document.getElementById("clave_privada");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}
</script>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
    animationEnabled: true,
    title:{
        text: "Grafica General"
    },
    axisX:{
        valueFormatString: "MMM",
        crosshair: {
            enabled: true,
            snapToDataPoint: true
        }
    },
    axisY: {
        title: "Gastos y Ingresos",
        includeZero: false,
        valueFormatString: "$##0.00MXN",
        crosshair: {
            enabled: true,
            snapToDataPoint: true,
            labelFormatter: function(e) {
                return "$" + CanvasJS.formatNumber(e.value, "##0.00MNX");
            }
        }
    },
    data: [{
        type: "area",
        xValueFormatString: "MMM",
        yValueFormatString: "$##0.00MNX",
        dataPoints: [
            { x: new Date(2019, 01), y: 1000 },
            { x: new Date(2019, 02), y: 2000 },
            { x: new Date(2019, 03), y: 1250 },
            { x: new Date(2019, 04), y: 984 },
            { x: new Date(2019, 05), y: 1500 },
            { x: new Date(2019, 06), y: 2500 },
            { x: new Date(2019, 07), y: 984 },
            { x: new Date(2019, 08), y: 500 },
            { x: new Date(2019, 09), y: 984 },
            { x: new Date(2019, 10), y: 2489 },
            { x: new Date(2019, 11), y: 3487 },
            { x: new Date(2019, 12), y: 1845 }
        ]},
        {
        type: "area",
        xValueFormatString: "MMM",
        yValueFormatString: "$##0.00",
        dataPoints: [
            { x: new Date(2019, 01), y: 1489 },
            { x: new Date(2019, 02), y: 2156 },
            { x: new Date(2019, 03), y: 1891 },
            { x: new Date(2019, 04), y: 1867 },
            { x: new Date(2019, 05), y: 2198 },
            { x: new Date(2019, 06), y: 3896 },
            { x: new Date(2019, 07), y: 3459 },
            { x: new Date(2019, 08), y: 1897 },
            { x: new Date(2019, 09), y: 1487 },
            { x: new Date(2019, 10), y: 1897 },
            { x: new Date(2019, 11), y: 1564 },
            { x: new Date(2019, 12), y: 1484 }
        ]
    }]
});
chart.render();

}
</script>
{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins col-lg-12">
                        <div class="ibox-title col-lg-12">
                            <h5>Firma de Contrato <small> Ayuda Contable</small></h5>
                            <div class="ibox-tools col-lg-12">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content col-lg-12">
                        {% if firmo %}
                        <h5>Bienvenido {{user.nombre_completo}}</h5><br>
                        <p>Nos agrada tenerte de vuelta
                        </p>
                        {% else %}
                        <h5>Es necesario su firma</h5>
                        <div class="col-lg-12">
                        <object data="/media/Contrato.pdf" type="application/pdf" class="col-lg-12"  height="200">
                            alt : <a href="/media/Contrato.pdf">Contrato.pdf</a>
                        </object>
                        <br>
                        <a href="/media/Contrato.pdf"> Ver contrato en una ventana nueva</a>
                        <br>
                        <a href="/media/Contrato.pdf" download> Descargar contrato</a>
                        </div>
                        <form class="m-t" role="form"  method="POST" action="{% url 'firmaUsuario' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" id="id" value="{{user.id}}">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <span class="btn btn-default btn-file"><span class="fileinput-new">Cargar e firma.cer</span>
                            <span class="fileinput-exists"></span><input type="file" name="e_firma_cer" id="e_firma_cer" id="id_e_firma_cer" accept=".cer" /></span>
                            <span class="fileinput-filename"></span>
                            <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">×</a>
                        </div>
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <span class="btn btn-default btn-file"><span class="fileinput-new">Cargar e firma.key</span>
                            <span class="fileinput-exists"></span><input type="file" name="e_firma_key" id="e_firma_key" id="id_e_firma_key" accept=".key"/></span>
                            <span class="fileinput-filename"></span>
                            <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">×</a>
                        </div> 
                        <div class="form-group">
                            <label>Clave Privada:</label> <i class="fa fa-question-circle-o" aria-hidden="true" title="Esta contraseña es la que corresponde la clave privada .key"></i>
                            <input type="password" placeholder="Ingrese clave" name="clave_privada" id="clave_privada" class="form-control"><input type="checkbox" onclick="ShowPass()">Mostrar Clave
                        </div>
                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Firmar</strong></button>
                        </form>
                        {% endif %}
                        {% if falta_ciec %}
                        <form class="m-t" role="form"  method="POST" action="{% url 'firmaCiec' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                        <p>Estimado Usuario nos ayuda aun mas con su clave CIEC para seguir generando las facturas de una forma facil.</p>
                        <p>Atte: Ayuda Contable</p>
                            <label>CIEC:</label> <i class="fa fa-question-circle-o" aria-hidden="true" title="Esta contraseña es la misma de su CIEC o CIEC fortalecida" ></i>
                            <input type="password" placeholder="Ingrese clave" name="ciec" id="ciec" class="form-control"><input type="checkbox" onclick="ShowCIEC()">Mostrar Clave
                        </div>
                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Firmar con CIEC</strong></button>
                        </form>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Graficas del Año
                                <small>de prueba</small>
                            </h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <div id="chartContainer">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            setTimeout(function() {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.success('Perfil Cargado con exito!', 'Bienvenido a Ayuda Contable');

            }, 1300);


            var data1 = [
                [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,30],[11,10],[12,13],[13,4],[14,3],[15,3],[16,6]
            ];
            var data2 = [
                [0,1],[1,0],[2,2],[3,0],[4,1],[5,3],[6,1],[7,5],[8,2],[9,3],[10,2],[11,1],[12,0],[13,2],[14,8],[15,0],[16,0]
            ];
            $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
                data1, data2
            ],
                    {
                        series: {
                            lines: {
                                show: false,
                                fill: true
                            },
                            splines: {
                                show: true,
                                tension: 0.4,
                                lineWidth: 1,
                                fill: 0.4
                            },
                            points: {
                                radius: 0,
                                show: true
                            },
                            shadowSize: 2
                        },
                        grid: {
                            hoverable: true,
                            clickable: true,
                            tickColor: "#d5d5d5",
                            borderWidth: 1,
                            color: '#d5d5d5'
                        },
                        colors: ["#1ab394", "#1C84C6"],
                        xaxis:{
                        },
                        yaxis: {
                            ticks: 4
                        },
                        tooltip: false
                    }
            );

            var doughnutData = {
                labels: ["App","Software","Laptop" ],
                datasets: [{
                    data: [300,50,100],
                    backgroundColor: ["#a3e1d4","#dedede","#9CC3DA"]
                }]
            } ;


            var doughnutOptions = {
                responsive: false,
                legend: {
                    display: false
                }
            };


            var ctx4 = document.getElementById("doughnutChart").getContext("2d");
            new Chart(ctx4, {type: 'doughnut', data: doughnutData, options:doughnutOptions});

            var doughnutData = {
                labels: ["App","Software","Laptop" ],
                datasets: [{
                    data: [70,27,85],
                    backgroundColor: ["#a3e1d4","#dedede","#9CC3DA"]
                }]
            } ;


            var doughnutOptions = {
                responsive: false,
                legend: {
                    display: false
                }
            };


            var ctx4 = document.getElementById("doughnutChart2").getContext("2d");
            new Chart(ctx4, {type: 'doughnut', data: doughnutData, options:doughnutOptions});

        });
    </script>
    <!-- CharJS con java script-->
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <!-- ChartJS-->
    <script type="text/javascript" src="{% static 'js/demo/chartjs-demo.js' %}" rel="stylesheet"></script>
    <script type="text/javascript" src="{% static 'js/plugins/chartJs/Chart.min.js' %}" rel="stylesheet"></script>
    <script type="text/javascript">
    #window.alert(5 + 6);
    </script>

{% endblock %}

templates/usuario/plantilla.html
{% extends 'base.html' %}
{% load static %}
  {% block title %}  {% endblock %}
  {% include "usuario/menu.html" %}
  {% block menubar %}{% endblock %}
{% block archivos %}
{% include 'verifiUsuario.html' %}
{% endblock %}
{% block content %}
{% endblock %}