AyudaContable/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
import usuario.views
import superadmin.views
import administrador.views
import usuario.views
#para las fotos
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.views import logout_then_login


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^superadmin/alta_de_administrador/$',superadmin.views.altaAdmin.as_view(), name='altaAdmin'),
    url(r'^superadmin/alta_de_usuario/$',superadmin.views.altaUsuario.as_view(), name='altaUsuario'),
    url(r'^superadmin/index/$',superadmin.views.index0, name='index0'),
    url(r'^administrador/index/$',administrador.views.index1,name='index1'),
    url(r'^administrador/subida/$',administrador.views.subidaXML,name='subidaXML'),
    url(r'^administrador/documentos/$',administrador.views.archivosDB, name='vistaDocumentos'),
    url(r'^administrador/usuarios/$',administrador.views.usuariosACargo,name='usuariosACargo'),
    url(r'^logout$', logout_then_login, name='logout' ),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], superadmin.views.protected_serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^',include('usuario.urls' )),
]

usuario/urls.py
from django.conf.urls import *
from usuario import views

urlpatterns = [
	url(r'^$',views.login, name='index'),
	url(r'^login/$',views.login, name='login'),
	url(r'^redi/$',views.redirecionDeEspacio,name='redi'),
	url(r'^usuario/index/$',views.index3,name='index3'),
	url(r'^usuario/documentos/$',views.archivosGeneral,name='vistaGeneral'),
	url(r'^usuario/documentosN/$',views.leerXMLN,name='vistaN'),
	url(r'^usuario/documentosE/$',views.leerXMLE,name='vistaE'),
	url(r'^usuario/documentosI/$',views.leerXMLI,name='vistaI'),
	url(r'^usuario/documentosP/$',views.leerXMLP,name='vistaP'),
	url(r'^usuario/documentosScript/$',views.leerXMLScript,name='vistaScript'),
	url(r'^usuario/firma/$',views.firmaContrato,name='firmaUsuario'),
	url(r'^usuario/firmaCiec/$',views.firmaCiec,name='firmaCiec'),
	url(r'^usuario/solicitar/$',views.solicitarFactura,name='solicitarFactura'),
	url(r'^usuario/referencia/$',views.generarOxxoPay,name='generarReferencia'),
	url(r'^webhook/$',views.webhook,name='webhook'),
]

administrador/models.py
from django.db import models

# Create your models here.
from superadmin.models import User
#from usuario.models import Usuario

def upload_e_firma(self, filename):
    return u'documentos/client_{0}/{1}'.format(self.usuario.id, filename)

class Administrador(models.Model):
    email = models.OneToOneField(User, on_delete=models.CASCADE)
    RFC = models.CharField(max_length=15,null=True)
    numero_de_empleado = models.IntegerField(null=True)
    foto_ine = models.FileField(upload_to='profiles',null=True)
    e_firma_key = models.FileField(upload_to=upload_e_firma,null=True)
    e_firma_cer = models.FileField(upload_to=upload_e_firma,null=True)
    puesto = models.CharField(max_length=20,null=True)
    
    def __str__(self):
        return self.email.nombre_completo
    
    class Meta:
        permissions = (
            ('is_admin', 'Is_Admin'),
            ('is_seller', 'Is_Seller'),
            )

usuario/models.py
from django.db import models

# Create your models here.
from superadmin.models import User
from administrador.models import Administrador
import os
from django_cryptography.fields import encrypt
import datetime
import conekta
from datetime import datetime 

def upload_e_firma(self, filename):
    return u'documentos/client_{0}/{1}'.format(self.email.id, filename)

class Usuario(models.Model):
    email = models.OneToOneField(User, on_delete=models.CASCADE)
    RFC = models.CharField(max_length=15,null=True)
    tipo_persona = models.CharField(max_length=15,null=True)
    razon_social = models.CharField(max_length=100,null=True,unique=True)
    direccion_fiscal = models.CharField(max_length=125, null=True)
    e_firma_key = models.FileField(upload_to=upload_e_firma,null=True)
    e_firma_cer = models.FileField(upload_to=upload_e_firma,null=True)
    clave_privada = encrypt(models.CharField(max_length=50))
    ciec = encrypt(models.CharField(max_length=50))
    contador = models.ForeignKey(Administrador, on_delete=models.CASCADE, blank=True, null=True,related_name="contador_personal")    
    def __str__(self):
        return self.email.nombre_completo
    
    class Meta:
        
        permissions = (
            ('is_user', 'Is_User'),
            )

class Cliente(models.Model):
	nombre_completo = models.CharField(max_length=200, null=True)
	razon_social = models.CharField(max_length=200,null=True)
	direccion = models.CharField(max_length=200, null=True)
	RFC = models.CharField(max_length=10,null=True)
	contador =  models.ForeignKey(Usuario,on_delete=models.CASCADE,blank=True, null=True, related_name="cliente_personal")

	def __str__(self):
		return self.RFC.nombre_completo

def upload_to(self, filename):
    return u'documentos/user_{0}/client_{1}/{2}'.format(self.contador.id,self.usuario.id, filename)

def upload_factura(self, filename):
    return u'documentos/user_{0}/client_{1}/{2}{3}-{4}/{5}'.format(self.contador.id,self.usuario.id,self.tipo,self.fecha.year,self.fecha.month, filename)

class Factura(models.Model):
    subido_el = models.DateTimeField(auto_now_add=True)
    contador = models.ForeignKey(Administrador, on_delete=models.CASCADE, blank=True, null=True,related_name="contadorACargo")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True,related_name="FDI")
    xml = models.FileField(upload_to=upload_factura)
    pdf = models.FileField(upload_to=upload_factura)
    fecha = models.DateTimeField(null=True)#format='%Y-%m',input_formats=['%Y-%m'], null=True)
    tipo = models.CharField(max_length=1,null=True)
    RFC = models.CharField(max_length=14,null=True)
    razon_social = models.CharField(max_length=100,null=True)
    vigente = models.BooleanField(default=True)
    sub_total = models.FloatField(null=True)
    total = models.FloatField(null=True)

    def __str__(self):
        return razon_social+str(fecha)

    def filename(self):
        return os.path.basename(self.xml.name)

#    def clean(self):
#        xml = self.cleaned_data.get("xml", False)
#        filetype = magic.from_buffer(xml.read())
#        if not "XML" in filetype:
#            raise ValidationError("File is not XML.")
#        return self.cleaned_data 

class PagoServicio(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True,related_name="cargo_a_usuario")
    referencia = models.CharField(max_length=100,null=True)
    id_orden = models.CharField(max_length=22,null=True)
    estado_de_la_orden = models.CharField(max_length=30,null=True)
    monto = models.CharField(max_length=10,null=True)
    fecha_creado = models.DateTimeField(default=datetime.now, blank=True)

    
    def __str__(self):
        return str(self.referencia)

administrador/forms.py
from django import forms
from usuario.models import Factura

def user_directory_path(instance, filename):
	# file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
	return 'user_{0}/{1}'.format(instance.user.id, filename)

class ArchivoForm(forms.ModelForm):
    class Meta:
        model = Factura
        fields = ('contador','usuario','xml',)
        widgets = {
        	'xml': forms.FileInput(attrs = {'class':'form-control','accept':'.pdf,.xml'}),
        }
        labels = {
			'xml' : 'Archivo:',
		}

class ArchivoForm1(forms.ModelForm):
    class Meta:
        model = Factura
        fields = ('contador','usuario','xml','pdf')
        widgets = {
            'xml': forms.FileInput(attrs = {'class':'form-control','accept':'.xml'}),
            'pdf': forms.FileInput(attrs = {'class':'form-control','accept':'.pdf'}),
            'contador': forms.TextInput(attrs = {'class':'form-control','readonly':'readonly'}),
        }
        labels = {
            'xml' : 'XML:',
            'pdf':'PDF:',
            'contador': 'Contador:',
        }

usuario/forms.py
from django import forms
from usuario.models import Usuario

class FirmaForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('e_firma_key', 'e_firma_cer','clave_privada',)

class FirmaCiec(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('ciec', )

administrador/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from administrador.forms import ArchivoForm1
from administrador.models import Administrador
from usuario.models import Factura
from superadmin.models import User
from django.conf import settings
from usuario.models import Usuario
import os
from django.contrib.auth.decorators import login_required
from xml.dom import minidom
import datetime
# Create your views here.

@login_required
def index1(request):    
	return render(request,'administrador/index.html')

def acomodar(archivoXML,factura):
	lectura= minidom.parse(archivoXML)
	lineas = lectura.getElementsByTagName("cfdi:Receptor")
	factura.RFC = lineas[0].getAttribute("Rfc")
	factura.razon_social = lineas[0].getAttribute("Nombre")
	lineas = lectura.getElementsByTagName("cfdi:Comprobante")
	tipoXML = lineas[0].getAttribute("TipoDeComprobante")
	factura.tipo = tipoXML
	fechaXML = lineas[0].getAttribute("Fecha")
	fechaXML=datetime.datetime.strptime(fechaXML,"%Y-%m-%dT%H:%M:%S")
	factura.fecha = fechaXML
	factura.sub_total = lineas[0].getAttribute("SubTotal")
	factura.total = lineas[0].getAttribute("Total")
	factura.save()

@login_required
def subidaXML(request):
	if request.method == 'POST':
		form = ArchivoForm1(request.POST, request.FILES)
		if form.is_valid():
			archivoXML = request.FILES['xml']
			factura = form.save(commit=False)
			#factura.save()
			acomodar(archivoXML,factura)
		return redirect('vistaDocumentos')
	else:
		form = ArchivoForm1() 
		usuario = User.objects.get(email=request.user.email)
		admin = Administrador.objects.get(email=usuario.id)
		return render(request, 'administrador/subida.html', {
			'form': form,
			'admin': admin
		})

@login_required
def archivos(request):
	usuario = User.objects.get(email=request.user.email)
	admin = Administrador.objects.get(email=usuario.id)
	url = settings.MEDIA_ROOT
	path=url+"/documentos/user_"+str(admin.id)
	file_list =os.listdir(path)
	return render(request,'administrador/documentos.html', {'documentos': file_list,'url':url})

@login_required
def archivosDB(request):
	usuario = User.objects.get(email=request.user.email)
	admin = Administrador.objects.get(email=usuario.id)
	archivos = Factura.objects.filter(contador=admin.id)
	return render(request,'administrador/documentosDB.html', {'documentos': archivos})

@login_required
def usuariosACargo(request):
	usuario = User.objects.get(email=request.user.email)
	admin = Administrador.objects.get(email=usuario.id)
	usuarios = Usuario.objects.filter(contador=admin.id)
	return render(request,'administrador/usuarios.html',{'usuarios':usuarios})

templates/administrador/documentos.html
{% extends 'base.html' %}
{% load static %}
  {% block title %} Inicio {% endblock %}
  {% block menubar %}{% include "administrador/menu.html" %}{% endblock %}

{% block content %}
    <main role="main" class="container">
    	<div class="container body-content" style="margin-top: 100px;">
        <main role="main">
            


<div class="container">
    <div class="login-form col-md-12 offset-md-0" style="border-radius:3%;">
        <h2 class="panel-title text-center">Subir archivos</h2>
        <hr>
        <h4 color="royalblue" class="text-center">XML o PDF</h4>
        <div style="text-align:center">
        <span id='message'></span>
        </div>
        
            <div id="singup" class="container tab-pane  active show" style="border-top:1px solid #2196f3; border-bottom:1px solid #2196f3; border-left:1px solid #2196f3; border-right:1px solid #2196f3;">
                <br>
            <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        
                        <label></label>
                        
                        <div class="form-group">
                            <span id='message'></span>
                            {% for documento in documentos %}
							<a href="{{documento}}"> {{documento}}</a>
							<br>
							{% endfor %}
  
                        </div>
                        <div class="form-group">
                            <div>
                               </div>
                        </div>
                    </div>
            </form>            </div>
     
    </div>
</div>

        </main>
    </div>

    <!--  Scripts-->
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>


    </main>

</style></defs><text x="0" y="2" style="font-weight:bold;font-size:2pt;font-family:Arial, Helvetica, Open Sans, sans-serif">32x32</text></svg>
{% endblock %}

templates/administrador/documentosDB.html
{% extends 'base.html' %}
{% load static %}
  {% block title %} Inicio {% endblock %}
  {% block menubar %}{% include "administrador/menu.html" %}{% endblock %}

{% block content %}
    <main role="main" class="container">
    	<div class="container body-content" style="margin-top: 100px;">
        <main role="main">
            


<div class="container">
    <div class="login-form col-md-12 offset-md-0" style="border-radius:3%;">
        <h2 class="panel-title text-center">Subir archivos</h2>
        <hr>
        <h4 color="royalblue" class="text-center">XML o PDF</h4>
        <div style="text-align:center">
        <span id='message'></span>
        </div>
        
            <div id="singup" class="container tab-pane  active show" style="border-top:1px solid #2196f3; border-bottom:1px solid #2196f3; border-left:1px solid #2196f3; border-right:1px solid #2196f3;">
                <br>
            <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        
                        <label></label>
                        
                        <div class="form-group">
                            <span id='message'></span>
                            {% for documento in documentos %}
							<a href="../../media/{{documento.xml}}"> {{documento.filename}}</a>
							<br>
							{% endfor %}
  
                        </div>
                        <div class="form-group">
                            <div>
                               </div>
                        </div>
                    </div>
            </form>            </div>
     
    </div>
</div>

        </main>
    </div>

    <!--  Scripts-->
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>


    </main>

</style></defs><text x="0" y="2" style="font-weight:bold;font-size:2pt;font-family:Arial, Helvetica, Open Sans, sans-serif"></text></svg>
{% endblock %}

templates/administrador/index.html
 {% extends 'base.html' %}
{% load static %}
{% block title %} Inicio {% endblock %}
{% block menubar %}{% include "administrador/menu.html" %}{% endblock %}

{% block content %}
    <main role="main" class="container">
      <div class="container body-content" style="margin-top: 100px;">
        <main role="main">
            


<div class="container">
    <div class="login-form col-md-12 offset-md-0" style="border-radius:3%;">
        <h2 class="panel-title text-center">Bienvenido {{user.nombre_completo}}</h2>
        <hr>
        <div style="text-align:center">
        <span id='message'></span>
        </div>
        
    </div>
</div>

        </main>
    </div>

    <!--  Scripts-->
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>


    </main>

</style></defs><text x="0" y="2" style="font-weight:bold;font-size:2pt;font-family:Arial, Helvetica, Open Sans, sans-serif"></text></svg>
{% endblock %}

        <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Basic Form</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="index.html">Home</a>
                        </li>
                        <li>
                            <a>Forms</a>
                        </li>
                        <li class="active">
                            <strong>Basic Form</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
            <div class="col-lg-7">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Basic form <small>Simple login form example</small></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Sign in</h3>
                                <p>Sign in today for more expirience.</p>
                                <form role="form">
                                    <div class="form-group"><label>Email</label> <input type="email" placeholder="Enter email" class="form-control"></div>
                                    <div class="form-group"><label>Password</label> <input type="password" placeholder="Password" class="form-control"></div>
                                    <div>
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Log in</strong></button>
                                        <label> <input type="checkbox" class="i-checks"> Remember me </label>
                                    </div>
                                </form>
                            </div>
                            <div class="col-sm-6"><h4>Not a member?</h4>
                                <p>You can create an account:</p>
                                <p class="text-center">
                                    <a href=""><i class="fa fa-sign-in big-icon"></i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="col-lg-5">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Horizontal form</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form class="form-horizontal">
                                <p>Sign in today for more expirience.</p>
                                <div class="form-group"><label class="col-lg-2 control-label">Email</label>

                                    <div class="col-lg-10"><input type="email" placeholder="Email" class="form-control"> <span class="help-block m-b-none">Example block-level help text here.</span>
                                    </div>
                                </div>
                                <div class="form-group"><label class="col-lg-2 control-label">Password</label>

                                    <div class="col-lg-10"><input type="password" placeholder="Password" class="form-control"></div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <div class="i-checks"><label> <input type="checkbox"><i></i> Remember me </label></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-sm btn-white" type="submit">Sign in</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Inline form</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form role="form" class="form-inline">
                                <div class="form-group">
                                    <label for="exampleInputEmail2" class="sr-only">Email address</label>
                                    <input type="email" placeholder="Enter email" id="exampleInputEmail2"
                                           class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword2" class="sr-only">Password</label>
                                    <input type="password" placeholder="Password" id="exampleInputPassword2"
                                           class="form-control">
                                </div>
                                <div class="checkbox m-r-xs">
                                    <input type="checkbox" id="checkbox1">
                                    <label for="checkbox1">
                                        Remember me
                                    </label>
                                </div>
                                <button class="btn btn-white" type="submit">Sign in</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Modal form <small>Example of login in modal box</small></h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <div class="text-center">
                            <a data-toggle="modal" class="btn btn-primary" href="#modal-form">Form in simple modal box</a>
                            </div>
                            <div id="modal-form" class="modal fade" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <div class="row">
                                                <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Sign in</h3>

                                                    <p>Sign in today for more expirience.</p>

                                                    <form role="form">
                                                        <div class="form-group"><label>Email</label> <input type="email" placeholder="Enter email" class="form-control"></div>
                                                        <div class="form-group"><label>Password</label> <input type="password" placeholder="Password" class="form-control"></div>
                                                        <div>
                                                            <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Log in</strong></button>
                                                            <label> <input type="checkbox" class="i-checks"> Remember me </label>
                                                        </div>
                                                    </form>
                                                </div>
                                                <div class="col-sm-6"><h4>Not a member?</h4>
                                                    <p>You can create an account:</p>
                                                    <p class="text-center">
                                                        <a href=""><i class="fa fa-sign-in big-icon"></i></a>
                                                    </p>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

templates/administrador/subida.html
{% extends 'base.html' %}
{% load static %}
  {% block title %} Inicio {% endblock %}
  {% block menubar %}{% include "administrador/menu.html" %}{% endblock %}

{% block content %}
    <main role="main" class="container">
    	<div class="container body-content" style="margin-top: 100px;">
        <main role="main">
            


<div class="container">
    <div class="login-form col-md-12 offset-md-0" style="border-radius:3%;">
        <h2 class="panel-title text-center">Subir archivos</h2>
        <hr>
        <h4 color="royalblue" class="text-center">XML o PDF</h4>
        <div style="text-align:center">
        <span id='message'></span>
        </div>
        
            <div id="singup" class="container tab-pane  active show" style="border-top:1px solid #2196f3; border-bottom:1px solid #2196f3; border-left:1px solid #2196f3; border-right:1px solid #2196f3;">
                <br>
            <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
                        <label></label>
                        
                        <div class="form-group">
                            <span id='message'></span>

   {% for fields in form%}
   {% if fields.name == 'contador' %}
        {{fields.label}}
        <input type="text" name="contador" class="form-control" readonly="readonly" id="id_contador" value="{{admin}}">
        <input type="hidden" name="contador" class="form-control" readonly="readonly" id="id_contador" value="{{admin.id}}">

   {% else %}
        {{fields.label}}
        {{fields}}
               <br>
        
   {% endif %}

   {% endfor %}
                        </div>
                        <div class="form-group">
                            <div>
                                <button id="registrar" type="submit" color="royalblue" class="btn btn-primary waves-effect waves-light">Subir</button>
                            </div>
                        </div>
                    </div>
            </form>            </div>
     
    </div>
</div>

        </main>
    </div>

    <!--  Scripts-->
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>


    </main>

</style></defs><text x="0" y="2" style="font-weight:bold;font-size:2pt;font-family:Arial, Helvetica, Open Sans, sans-serif">32x32</text></svg>
{% endblock %}